### ISSUE TITLE
Проблема с UNIX(Linux) системами

### ISSUE THREAD

**Issue by simply-kel** [simply-kel/SimplyStatus#14]
При запуске игры на Linux, вылетает ошибка запуска библиотеки DiscordIPC
```log
--- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2023-12-03 15:04:17
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'simplystatus'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:466)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoClassDefFoundError: org/newsclub/net/unix/AFUNIXSocketAddress
	at com.jagrosh.discordipc.entities.pipe.Pipe.createPipe(Pipe.java:195)
	at com.jagrosh.discordipc.entities.pipe.Pipe.openPipe(Pipe.java:77)
	at com.jagrosh.discordipc.IPCClient.connect(IPCClient.java:375)
	at ru.kelcuprum.simplystatus.SimplyStatus.registerApplications(SimplyStatus.java:118)
	at ru.kelcuprum.simplystatus.SimplyStatus.onInitializeClient(SimplyStatus.java:107)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	... 9 more
Caused by: java.lang.ClassNotFoundException: org.newsclub.net.unix.AFUNIXSocketAddress
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 15 more

```

**Comment by simply-kel** [comment]
Исправлено в [commit](https://github.com/simply-kel/SimplyStatus/commit/a0e27ca0d4d27ccdbf71741dee4343a3234f5dcc)
